### ISSUE TITLE
Getting errors while installing dependencies

### ISSUE THREAD

**Issue by GTziolas** [Marinto-Richee/AI-Image-Annotation#1]
I'm getting multiple errors while executing `pip install -r requirements.txt`:

1) All of the packages that look like `'C:\\home\\conda\\feedstock_root\\build_artifacts\\asttokens_1698341106958\\work'` give the error: `ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory:`

2) The package `pywin32==227` gives the error: 
`ERROR: Could not find a version that satisfies the requirement pywin32==227 (from versions: 303, 304, 305, 306) ERROR: No matching distribution found for pywin32==227`

**Comment by Marinto-Richee** [comment]
The issues have been fixed.
